# Generated by Django 5.1.3 on 2024-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
